app_name = "frappe_dwf"
app_title = "Frappe DWF"
app_publisher = "YourOrg"
app_description = "Distributed Workflow Framework (DWF) implementation for IHE on Frappe"
app_icon = "octicon octicon-organization"
app_color = "grey"
app_email = "devops@yourorg.example"
app_license = "MIT"
